# Apartado 1: Imagen basada en PHP oficial (incluye Apache)
FROM php:8.2-apache

# Copiar la aplicación PHP desde el directorio local 'app/' al directorio web del contenedor
COPY app/ /var/www/html/

# Exponer el puerto 80
EXPOSE 80
